[package]
name = "flasher-stub"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"

[dependencies]
esp-backtrace = { version = "0.3.0", features = ["exception-handler", "panic-handler", "print-uart"] }
esp32-hal = { version = "0.5.0", optional = true }
esp32c3-hal = { version = "0.2.0", optional = true }
esp32s3-hal = { version = "0.2.0", optional = true }
heapless = "0.7.16"
md-5 = { version = "0.10.5", default-features = false }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "0.9.0"
riscv-rt = "0.9.0"

[target.'cfg(target_arch = "xtensa")'.dependencies]
xtensa-lx = "0.7.0"
xtensa-lx-rt = "0.13.0"

[dev-dependencies]
assert2 = "0.3.6"
matches = "0.1.9"
mockall = "0.11.2"
mockall_double = "0.3.0"

[features]
esp32 = ["esp32-hal", "esp-backtrace/esp32"]
esp32c3 = ["esp32c3-hal", "esp-backtrace/esp32c3"]
esp32s3 = ["esp32s3-hal", "esp-backtrace/esp32s3"]

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
